os:
  - linux
cache:
  directories:
    - "$HOME/.composer/cache"
language: php
php:
  - 7.2
install:
  - composer install
  - php artisan migrate --seed
script:
  - phpunit --configuration phpunit.xml --coverage-text
deploy:
  provider: azure_web_apps
  verbose: true
  before_deploy: "git push origin master:refs/heads/master"
notifications:
  email:
    recipients: sofialundkvist@outlook.com
