os:
  - linux
cache:
  directories:
    - "$HOME/.composer/cache"
language: php
php:
  - 7.1
install:
  - composer install
  - php artisan migrate
script:
  - phpunit --configuration phpunit.xml --coverage-text
deploy:
  provider: azure_web_apps
  verbose: true
notifications:
  email:
    recipients: sofialundkvist@outlook.com
